/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TokenProxyInterface extends ethers.utils.Interface {
  functions: {
    "createToken(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "createToken", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class TokenProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TokenProxyInterface;

  functions: {
    createToken(
      recipient: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createToken(address)"(
      recipient: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  createToken(
    recipient: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createToken(address)"(
    recipient: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    createToken(recipient: string, overrides?: CallOverrides): Promise<string>;

    "createToken(address)"(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createToken(recipient: string, overrides?: Overrides): Promise<BigNumber>;

    "createToken(address)"(
      recipient: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createToken(
      recipient: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createToken(address)"(
      recipient: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
